apiVersion: v1
kind: PersistentVolume
metadata:
  name: database_pv_volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database_pv_volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi